### ISSUE TITLE
Add Base plugin functionality for processing the user-provided samples file

### ISSUE THREAD

**Issue by carolyncaron** [TripalCultivate/TripalCultivate-Genetics#23]
This is a method in the base plugin to process the samples file and lookup and/or insert germplasm into the database.

Code from T3: https://github.com/UofS-Pulse-Binfo/genotypes_loader/blob/db08d0a00d5606088fef84f830e10061c04af7f3/genotypes_loader.drush.inc#L284-L427

Parameters: none

Returns: a protected property of the class; an associative array with the sample name as the key, stock_id as the value

**Comment by laceysanderson** [comment]
Completed!
